# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('profile_pic', models.CharField(blank=True, max_length=500)),
                ('communities', models.ManyToManyField(to='core.Community')),
                ('friends', models.ManyToManyField(related_name='_user_friends_+', to='core.User')),
            ],
        ),
    ]
